---
# tasks file for nginx-web
- name: NGINX | Install EPEL Repo package from standart repo
  yum:
    name: epel-release
    state: present
  tags:
    - epel-package
    - packages

- name: NGINX | Install NGINX package from EPEL Repo
  yum:
    name: nginx
    state: latest
  notify:
    - restart nginx
  tags:
    - nginx-package
    - packages

- name: NGINX | Create NGINX config file from template
  template:
    src=nginx.conf.j2
    dest={{ destin_folder }}/nginx.conf
    mode=0555
  notify:
    - reload nginx
  tags:
    - nginx-configuration
